services:
  - type: web
    name: discord-webhook-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
        
